version: '3.1'
services:
  dev-db:
    image: postgis/postgis
    restart: always
    ports:
      - 9000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: taxi24
    networks:
      - taxi24-api
  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
    networks:
      - taxi24-api
networks:
  taxi24-api: